### ISSUE TITLE
[FEATURE] provide logs for the NB containers

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlaedge/agent#94]
**Is your feature request related to a problem? Please describe.**
When issues arise, we always need to look at NBs logs, so we need to SSH.

**Describe the solution you'd like**
It would be better to access such logs remotely, from Nuvla, even if just a small snippet of the latest logs. Either on demand, or as part of the telemetry

**Comment by konstan** [comment]
Just to +1 it, when ESAC talks about the ground stations collecting data, they have an explicit requirement on the exploitation platform to have the searchable logs from the stations available in the mata-data catalogue.

**Comment by ignacio-penas** [comment]
The current implementatioon allows Nuvla to remotely connect to the docker socket using the cetificates and retrieve directly the logs from there. 

While this implementation grants access to the Edge when the device is operative, if the connection with it is lost there is no way to assess what went wrong.

Options:

1.- Unify the logging system of the NuvlaEdge in a single DB, then having the telemtry report in every heartbeat the las X lines of logs on every contiainer. Allow configurability of refresh period and log level for every component.
Pros:
- Historic logging saved

Cons:
- Need to add another component (DB) will increase the memory used. (There are really low memory demanding options, and it could be used for improving NuvlaEdge general implementation)
- If there is a connection loss

2.- Having a Trigger to automatically report ERROR level loggings directly to Nuvla. Leave the rest as they are now
Pros:
- More accurate error report and better QoS

3.- Combining both options will produce the most robust system. Not having to rely in the telemetry to report errors and at the same time the capability to track further logs will help on debugging.

**Comment by konstan** [comment]
This was implemented
 
![Screenshot 2022-11-09 at 09 25 55](https://user-images.githubusercontent.com/353767/200777557-63d83104-56cd-42eb-8f4e-e1ee6c04937b.png)

The issue wasn't auto-closed because the PR https://github.com/nuvla/ui/pull/782 on UI where this issue was mentioned was closed w/o merge. The final implementation was done in different branches/PRs.

A new issue will be created to consider points by @ignacio-penas  from https://github.com/nuvlaedge/agent/issues/94#issuecomment-1176143265
